Name - Ishita Sharma
CWID - 50224923

In [9]:
#libraries required in the data for the application of the model
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import model_selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from pandas.plotting import scatter_matrix
from scipy import stats
import numpy as np


In [10]:
#loading the data 
#Doing some essential changes inorder to apply classifier to the model
df = pd.read_csv("Breast_cancer_data.csv",header = 0)
df = df.replace({'B':0,'M':1})
df = df.dropna(axis = 1)
print(df)
print(df.head())
print()
print()
print(df.tail())

print(df.columns)

           id  diagnosis  radius_mean  texture_mean  perimeter_mean  \
0      842302          1       17.990         10.38          122.80   
1      842517          1       20.570         17.77          132.90   
2    84300903          1       19.690         21.25          130.00   
3    84348301          1       11.420         20.38           77.58   
4    84358402          1       20.290         14.34          135.10   
5      843786          1       12.450         15.70           82.57   
6      844359          1       18.250         19.98          119.60   
7    84458202          1       13.710         20.83           90.20   
8      844981          1       13.000         21.82           87.50   
9    84501001          1       12.460         24.04           83.97   
10     845636          1       16.020         23.24          102.70   
11   84610002          1       15.780         17.89          103.60   
12     846226          1       19.170         24.80          132.40   
13    

In [11]:
#here first of all to apply the train_test_split I made sure that I can combine the 
#independent data(features) in X
#dependent data(predictor or target) in Y which is the diagnosis that is 'B' or 'M'
#I used .values so that I can get the array(vector) so I can easily split the data in train and test
X = df.iloc[:, 2:31].values 
Y = df.iloc[:, 1].values 


In [12]:
#Splitting the data on train and test
#Making the model ready for the train data processing
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)


In [13]:
#Data preprocessing(Feature scaling)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


Feature scaling for my data so that the train and test data are better in the scale 
So that all the prediction on test data can be done with accuracy 

In [25]:
def models(X_train,Y_train):
  
  #Using Logistic Regression Algorithm to the Training Set
    log_reg = LogisticRegression(random_state = 0,solver = 'lbfgs')
    log_reg.fit(X_train, Y_train)
  
  #Using KNeighborsClassifier(Nearest Neighbor algorithm)
  #help(KNeighborsClassifier)
    knn_model = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    knn_model.fit(X_train, Y_train)

  #Using SVC method to apply Support Vector Machine Algorithm
  #in SVM we have many kernels so here I am using the linear and rbf
    svc_linear = SVC(kernel = 'linear', random_state = 0)
    svc_linear.fit(X_train, Y_train)
    
    svc_rbf = SVC(kernel = 'rbf', random_state = 0)
    svc_rbf.fit(X_train, Y_train)

    
  #Using DecisionTreeClassifier(Decision Tree Algorithm)
    Dec_tree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    Dec_tree.fit(X_train, Y_train)

  #Using RandomForestClassifier(one of the best consisdered classifier)
    Rand_forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    Rand_forest.fit(X_train, Y_train)
  
  #print model accuracy on the training data.
    #print("The Training accuracy of the model with different models is as follows:")
    print('[1]Logistic Regression:', log_reg.score(X_train, Y_train))
    print('[2]KNearest Neighbor:', knn_model.score(X_train, Y_train))
    print('[3]Support Vector Machine (Linear Classifier):', svc_linear.score(X_train, Y_train))
    print('[4]Support Vector Machine (RBF Classifier):',svc_rbf.score(X_train, Y_train))
    print('[5]Decision Tree Classifier: ', Dec_tree.score(X_train, Y_train))
    print('[6]Random Forest Classifier:', Rand_forest.score(X_train, Y_train))
  
    return log_reg, knn_model, svc_linear,svc_rbf , Dec_tree, Rand_forest












In [26]:
 model = models(X_train,Y_train)


[1]Logistic Regression: 0.9906103286384976
[2]KNearest Neighbor: 0.9765258215962441
[3]Support Vector Machine (Linear Classifier): 0.9882629107981221
[4]Support Vector Machine (RBF Classifier): 0.9835680751173709
[5]Decision Tree Classifier:  1.0
[6]Random Forest Classifier: 0.9953051643192489


From above we can see that usually the RandomForest Classifier is considered to be the best classifier 
but apparently the best classifier which can be used for the classification of the Malingant(M) and Bengin(B)
is Decision Tree with the accuracy of perfect '1'
Also this is the result with the sklearn library
We can also compare it without the using of the sklearn library as well
Usually the RandomForest is one of the type of the ensemble methods of the Decision Tree 
So therefore it is always best using for the categorical kind of data the Decision Tree Classifier


After this I will apply the model to the test data and try to predict which is the goal of the whole model making 
such that I can make a Classification system
I will first use Confusion Matrix(cm) so as to get the accuracy
Then using the libraries of sklearn I can generate the classification report of the accuracy

In [33]:
#Using ConfusionMatrix
#cm_log = confusion_matrix(Y_test, model[0].predict(X_test))
#cm_knn = confusion_matrix(Y_test, model[1].predict(X_test))
#cm_svm_lin = confusion_matrix(Y_test, model[3].predict(X_test))
#cm_svm_rbf = confusion_matrix(Y_test,model[4].predict(X_test))
#cm_DT = confusion_matrix(Y_test, model[5].predict(X_test))
#cm_RandomForest = confusion_matrix(Y_test, model[6].predict(X_test))

#It is always more conviennet to put all the model in for loop since we are finding the confusion matrics for all 
for m in range(len(model)):
    cm = confusion_matrix(Y_test, model[m].predict(X_test))
    True_Neg = cm[0][0]
    True_Pos = cm[1][1]
    False_Neg = cm[1][0]
    False_Pos = cm[0][1]
    
    total = True_Neg+True_Pos+False_Neg+False_Pos
    accuracy = (True_Neg + True_Pos)/total
    print(cm)
    print()
    print('Model[{}] Testing Accuracy = "{}!"'.format(m, accuracy))
    print('------------------------------------------')
    print()



[[86  4]
 [ 4 49]]

Model[0] Testing Accuracy = "0.9440559440559441!"
------------------------------------------

[[89  1]
 [ 5 48]]

Model[1] Testing Accuracy = "0.958041958041958!"
------------------------------------------

[[87  3]
 [ 2 51]]

Model[2] Testing Accuracy = "0.965034965034965!"
------------------------------------------

[[88  2]
 [ 3 50]]

Model[3] Testing Accuracy = "0.965034965034965!"
------------------------------------------

[[84  6]
 [ 1 52]]

Model[4] Testing Accuracy = "0.951048951048951!"
------------------------------------------

[[87  3]
 [ 2 51]]

Model[5] Testing Accuracy = "0.965034965034965!"
------------------------------------------



In [34]:
#After this we can produce the classification report,for which the library I have added above in the first block

for i in range(len(model)):
  print('Model ',i)
  #Check precision, recall, f1-score
  print( classification_report(Y_test, model[i].predict(X_test)) )
  #Another way to get the models accuracy on the test data
  print( accuracy_score(Y_test, model[i].predict(X_test)))
  print()#Print a new line


Model  0
              precision    recall  f1-score   support

           0       0.96      0.96      0.96        90
           1       0.92      0.92      0.92        53

    accuracy                           0.94       143
   macro avg       0.94      0.94      0.94       143
weighted avg       0.94      0.94      0.94       143

0.9440559440559441

Model  1
              precision    recall  f1-score   support

           0       0.95      0.99      0.97        90
           1       0.98      0.91      0.94        53

    accuracy                           0.96       143
   macro avg       0.96      0.95      0.95       143
weighted avg       0.96      0.96      0.96       143

0.958041958041958

Model  2
              precision    recall  f1-score   support

           0       0.98      0.97      0.97        90
           1       0.94      0.96      0.95        53

    accuracy                           0.97       143
   macro avg       0.96      0.96      0.96       143
weighted

In [36]:
#based on the accuracy score (Random forest is the best classifier)
pred = model[5].predict(X_test)
print(pred)
#Print a space
print()
#Print the actual values
print(Y_test)

[1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 0 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 0 1 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 0 1 1 1 0 0 1 0 0
 1 0 0 0 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 1 0
 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1]

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0 1 1 1 0 0 1 0 1 1 1 0 0 1 0 1
 1 0 0 0 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 1 1 0
 1 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1]


I found the random forest is the best classifier
After this I made another notebook in which I try doing feature selection with random forest classifier
The notebook is named Feature_Selection using RandomForest